from text import chinese, japanese, cleaned_text_to_sequence


language_module_map = {"ZH": chinese, "JP": japanese}

# TODO:I think I should try to replace the cleaned text sequence used for training
#  with a new one generated by zh_ja_mixture_cleaner.But for the first release, just use it for now to avoid problems


# pyopenjtalk should use the same symbol system(perhaps?)So keep this unchanged
def clean_text(text, language):
    language_module = language_module_map[language]
    norm_text = language_module.text_normalize(text)
    phones, tones, word2ph = language_module.g2p(norm_text)
    return norm_text, phones, tones, word2ph


def clean_text_bert(text, language):
    language_module = language_module_map[language]
    norm_text = language_module.text_normalize(text)
    phones, tones, word2ph = language_module.g2p(norm_text)
    bert = language_module.get_bert_feature(norm_text, word2ph)
    return phones, tones, bert


def text_to_sequence(text, language):
    norm_text, phones, tones, word2ph = clean_text(text, language)
    return cleaned_text_to_sequence(phones, tones, language)


if __name__ == "__main__":
    pass
